openapi: 3.0.0
info:
  title: ShutterSync
  description: ShutterSync aims to address the need for professional photographers to efficiently share and collaborate on their work with clients, enhancing client engagement and project management.
  version: '1'

servers:
  - description: ShutterSync
    url: https://virtserver.swaggerhub.com/ShutterSync/ShutterSync/1
  - url: http://localhost:3000
    description: Development server
  - url: https://api.shuttersync.live
    description: Production server

tags:
  - name: Auth
    description: Authentication operations and parameters
  - name: User
    description: Operations related to user management
  - name: Album
    description: Operations related to album management
  - name: Photo
    description: Operations related to photo management

components:
  securitySchemes:
    apiKey:
      type: apiKey
      name: x-api-key
      in: header
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT  
  schemas:
    User:
      type: object
      required:
        - name
        - email
        - password
      properties:
        name:
          type: string
          description: The name of the user
        email:
          type: string
          format: email
          description: The email address of the user
        password:
          type: string
          format: password
          description: The password of the user (must be at least 6 characters)
        avatar:
          type: string
          description: URL of the user's avatar
      example:
        name: John Doe
        email: john@example.com
        password: password123
        avatar: https://example.com/avatar.jpg

    Album:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: The name of the album
      example:
        name: Vacation 2022

    Photo:
      type: object
      required:
        - album
        - imageUrl
      properties:
        album:
          type: string
          description: The ID of the album to which the photo belongs
        imageUrl:
          type: string
          description: URL of the photo
        caption:
          type: string
          description: Caption for the photo
        size:
          type: string
          description: Size of the photo
        public_id:
          type: string
          description: Public ID of the photo (if applicable)
        name:
          type: string
          description: Name of the photo
      example:
        album: 5f4e5e012739b21425b61e0a
        imageUrl: https://example.com/photo.jpg
        caption: Sunset at the beach
        size: 1024x768
        public_id: abc123def456
        name: SunsetPhoto

  parameters:
    userId:
      in: path
      name: userId
      required: true
      description: ID of the user
      schema:
        type: string
    albumId:
      in: path
      name: albumId
      required: true
      description: ID of the album
      schema:
        type: string
    photoId:
      in: path
      name: photoId
      required: true
      description: ID of the photo
      schema:
        type: string




security:
  - apiKey: []

paths:
  /api/users:
    post:
      summary: Create a new user
      description: Endpoint to create a new user.
      tags:
        - User
      security:
        - apiKey: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created successfully.
          content:
            application/json:
              example:
                _id: 5f4e5e012739b21425b61e0a
                name: John Doe
                email: john@example.com
                avatar: https://example.com/avatar.jpg
        '400':
          description: Bad request. Check the request payload.
        '500':
          description: Internal server error.

    get:
      summary: Get a list of users
      description: Endpoint to retrieve a list of all users.
      tags:
        - User
      security:
        - apiKey: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                users:
                  - _id: 5f4e5e012739b21425b61e0a
                    name: John Doe
                    email: john@example.com
                    avatar: https://example.com/avatar.jpg
                  - _id: 5f4e5e012739b21425b61e0b
                    name: Jane Doe
                    email: jane@example.com
                    avatar: https://example.com/avatar.jpg
        '500':
          description: Internal server error.

  /api/users/{userId}:
    get:
      summary: Get a user by ID
      description: Endpoint to retrieve a user by their ID.
      tags:
        - User
      security:
        - apiKey: []
        - jwt: []
      parameters:
        - $ref: '#/components/parameters/userId'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                _id: 5f4e5e012739b21425b61e0a
                name: John Doe
                email: john@example.com
                avatar: https://example.com/avatar.jpg
        '404':
          description: User not found.
        '500':
          description: Internal server error.

    put:
      summary: Update a user by ID
      description: Endpoint to update a user by their ID.
      tags:
        - User
      security:
        - apiKey: []
        - jwt: []
      parameters:
        - $ref: '#/components/parameters/userId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User updated successfully.
          content:
            application/json:
              example:
                _id: 5f4e5e012739b21425b61e0a
                name: Updated Name
                email: john@example.com
                avatar: https://example.com/avatar.jpg
        '400':
          description: Bad request. Check the request payload.
        '404':
          description: User not found.
        '500':
          description: Internal server error.

    delete:
      summary: Delete a user by ID
      description: Endpoint to delete a user by their ID.
      tags:
        - User
      security:
        - apiKey: []
        - jwt: []
      parameters:
        - $ref: '#/components/parameters/userId'
      responses:
        '204':
          description: User deleted successfully.
        '404':
          description: User not found.
        '500':
          description: Internal server error.

  /api/users/{userId}/albums:
    post:
      summary: Create a new album
      description: Endpoint to create a new album.
      tags:
        - Album
      security:
        - apiKey: []
      parameters:
        - $ref: '#/components/parameters/userId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Album'
      responses:
        '201':
          description: Album created successfully.
          content:
            application/json:
              example:
                _id: 5f4e5e012739b21425b61e0a
                name: Vacation 2022
        '400':
          description: Bad request. Check the request payload.
        '500':
          description: Internal server error.

    get:
      summary: Get a list of albums
      description: Endpoint to retrieve a list of all albums.
      tags:
        - Album
      security:
        - apiKey: []
      parameters:
        - $ref: '#/components/parameters/userId'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                albums:
                  - _id: 5f4e5e012739b21425b61e0a
                    name: Vacation 2022
                  - _id: 5f4e5e012739b21425b61e0b
                    name: Wedding 2021
        '500':
          description: Internal server error.

  /api/users/{userId}/albums/{albumId}:
    get:
      summary: Get an album
      description: Endpoint to retrieve an album by its ID.
      tags:
        - Album
      security:
        - apiKey: []
      parameters:
        - $ref: '#/components/parameters/userId'
        - $ref: '#/components/parameters/albumId'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                _id: 5f4e5e012739b21425b61e0a
                name: Vacation 2022
        '404':
          description: Album not found.
        '500':
          description: Internal server error.

    put:
      summary: Update an album
      description: Endpoint to update an album
      tags:
        - Album
      security:
        - apiKey: []
      parameters:
        - $ref: '#/components/parameters/userId'
        - $ref: '#/components/parameters/albumId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Album'
      responses:
        '200':
          description: User updated successfully.
          content:
            application/json:
              example:
                _id: 5f4e5e012739b21425b61e0a
                name: Updated Name
        '400':
          description: Error check request payload!
        '500':
          description: Internal Server Error
    delete:
      summary: Delete an album
      description: Endpoint to delete an album
      tags:
        - Album
      security:
        - apiKey: []
      parameters:
        - $ref: '#/components/parameters/userId'
        - $ref: '#/components/parameters/albumId'
      responses:
        '204':
          description: Album deleted successfully.
        '500':
          description: Internal Server Error
    
  /api/users/{userId}/albums/{albumId}/photo:
    post:
      summary: Add a photo to an album
      description: Add a new photo to a particular album
      tags:
        - Album
        - Photo
      security:
        - apiKey: []
      parameters:
        - $ref: '#/components/parameters/userId'
        - $ref: '#/components/parameters/albumId'
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                photo:
                  type: string
                  format: binary
      responses:
        '200':
          description: OK

  /api/users/{userId}/albums/{albumId}/photo/{photoId}:
    delete:
      summary: Delete a photo from an album
      description: Delete a photo from a particular album
      tags:
        - Photo
      security:
        - apiKey: []
      parameters:
        - $ref: '#/components/parameters/userId'
        - $ref: '#/components/parameters/albumId'
        - $ref: '#/components/parameters/photoId'
      responses:
        '204':
          description: No Content
  /api/photos/:photoId:
    put:
      summary: Update a photo in an album
      description: Update details of a photo in a particular album
      tags:
        - Photo
      security:
        - apiKey: []
      parameters:
        - $ref: '#/components/parameters/photoId'
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                photo:
                  type: string
                  format: binary
      responses:
        '200':
          description: OK

    get:
      summary: Get a photo from an album
      description: Get details of a photo in a particular album
      tags:
        - Photo
      security:
        - apiKey: []
      parameters:
        - $ref: '#/components/parameters/photoId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Photo'
    delete:
      summary: Delete a photo from an album
      description: Delete a photo from a particular album
      tags:
        - Photo
      security:
        - apiKey: []
      parameters:
        - $ref: '#/components/parameters/photoId'
      responses:
        '204':
          description: No Content
      

  /auth/signin:
    post:
      summary: Sign in
      description: Endpoint to sign in a user.
      tags:
        - Auth
      security:
        - apiKey: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  description: The email address of the user
                password:
                  type: string
                  format: password
                  description: The password of the user (must be at least 6 characters)
            example:
              email: testmail@testmail.com
              password: password123
      responses:
        '200':
          description: User signed in successfully.
          content:
            application/json:
              example:
                token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjRlNWUwMTI3MzliMjE0MjViNjFlMGEiLCJpYXQiOjE2MDA5N
                name: John Doe
                email: testmail@testmail.com
                avatar: https://example.com/avatar.jpg
        '400':
          description: Bad request. Check the request payload.
        '401':
          description: Unauthorized. Invalid credentials.
        '500':
          description: Internal server error.
    
  /auth/signout:
    get:
      summary: Sign out
      description: Endpoint to sign out a user.
      tags:
        - Auth
      security:
        - apiKey: []
      responses:
        '200':
          description: User signed out successfully.
        '500':
          description: Internal server error.
